CREATE DATABASE "PGC"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

\c PGC

CREATE TYPE ZONES AS ENUM ('Centro', 'Leste', 'Norte', 'Oeste', 'Sul');

CREATE TABLE DEVICES_INVENTORY (
	DEVICE_ID SMALLSERIAL PRIMARY KEY,
	COORDINATES CHARACTER VARYING(50) NOT NULL,
	STREET CHARACTER VARYING(50) NOT NULL,
	DISTRICT CHARACTER VARYING(25) NOT NULL,
	ZONE ZONES NOT NULL,
	STATUS BOOLEAN NOT NULL,
	IS_REAL BOOLEAN NOT NULL
);

CREATE TABLE SENSORS_DATA_REAL_TIME (
	DATA_ID SERIAL PRIMARY KEY,
	DEVICE_ID SMALLSERIAL NOT NULL,
	VOLTAGE SMALLINT NOT NULL,
	CURRENT REAL NOT NULL,
	LIGHTNESS SMALLINT NOT NULL,
	RELE_STATE BOOLEAN NOT NULL,
	INSERTION_TIME TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES_INVENTORY(DEVICE_ID)
);

CREATE TABLE SENSORS_DATA_INTERVAL (
	DATA_ID SERIAL PRIMARY KEY,
	DEVICE_ID SMALLSERIAL NOT NULL,
	VOLTAGE_MIN SMALLINT NOT NULL,	
	VOLTAGE_MAX SMALLINT NOT NULL,
	VOLTAGE_AVG SMALLINT NOT NULL,
	CURRENT_MIN REAL NOT NULL,	
	CURRENT_MAX REAL NOT NULL,
	CURRENT_AVG REAL NOT NULL,
	LIGHTNESS_MIN SMALLINT NOT NULL,	
	LIGHTNESS_MAX SMALLINT NOT NULL,
	LIGHTNESS_AVG SMALLINT NOT NULL,
	POWER_MIN SMALLINT NOT NULL,
	POWER_MAX SMALLINT NOT NULL,
	POWER_AVG SMALLINT NOT NULL,
	POWER_EXPEND REAL NOT NULL,
	NUM_REGISTRIES SMALLINT NOT NULL,
	INSERTION_TIME TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES_INVENTORY(DEVICE_ID)
);